dist: xenial # Required for Python 3.7, see https://github.com/travis-ci/travis-ci/issues/9069
language: python
python:
  - "2.7"
  - "3.7"
install:
  - "pip install -r requirements.txt"
  - "pip install flake8"
before_script: "flake8 --max-line-length=100 --exclude=parsetab.py ."
script: "python tests.py"
